[tools]
dotnet = '8'
python = '3.10'
ruby = '3.4.2'
go = '1.26.0'
rust = "1.91.1"

[env]
_.python.venv = '{{env.HOME}}/.venv'

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
experimental = true
